language: ruby

rvm:
  - 2.4.1

cache: bundler

gemfile:
  - Gemfile
services:
  - mysql
before_install:
  - 'rm ${BUNDLE_GEMFILE}.lock'
  - gem update --system

after_install:
  - rails spring rspec

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

notifications:
  email:
    on_pull_request: false
    on_success: change
    on_failure: always