version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/task-manager-api
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    links:
      - db
    stdin_open: true
    tty: true

volumes:
  db-data:
    driver: local
  bundler:
    driver: local
