version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
    restart: always
    ports:
      - '3306:3306'

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/task-manager-api
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true
