default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: mysql

development:
  <<: *default
  database: task_manager_api_development

test:
  <<: *default
  database: task_manager_api_test

production:
  <<: *default
  database: task_manager_api_production
